package com.gome.pricealarm.common.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2016-04-14T16:52:43.919+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "DomainService", 
                  wsdlLocation = "http://10.58.50.212:8998/DomainService.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class DomainService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "DomainService");
    public final static QName DomainServiceSoap12 = new QName("http://tempuri.org/", "DomainServiceSoap12");
    public final static QName DomainServiceSoap = new QName("http://tempuri.org/", "DomainServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.58.50.212:8998/DomainService.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DomainService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.58.50.212:8998/DomainService.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public DomainService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DomainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DomainService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DomainService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DomainService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DomainService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DomainServiceSoap
     */
    @WebEndpoint(name = "DomainServiceSoap12")
    public DomainServiceSoap getDomainServiceSoap12() {
        return super.getPort(DomainServiceSoap12, DomainServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainServiceSoap
     */
    @WebEndpoint(name = "DomainServiceSoap12")
    public DomainServiceSoap getDomainServiceSoap12(WebServiceFeature... features) {
        return super.getPort(DomainServiceSoap12, DomainServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns DomainServiceSoap
     */
    @WebEndpoint(name = "DomainServiceSoap")
    public DomainServiceSoap getDomainServiceSoap() {
        return super.getPort(DomainServiceSoap, DomainServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DomainServiceSoap
     */
    @WebEndpoint(name = "DomainServiceSoap")
    public DomainServiceSoap getDomainServiceSoap(WebServiceFeature... features) {
        return super.getPort(DomainServiceSoap, DomainServiceSoap.class, features);
    }

}
